apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: social-proof-system
  labels:
    app: clickhouse
    environment: ${ENVIRONMENT}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard-rwo

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
  namespace: social-proof-system
  labels:
    app: clickhouse
    environment: ${ENVIRONMENT}
data:
  config.xml: |
    <?xml version="1.0"?>
    <clickhouse>
        <logger>
            <level>information</level>
            <console>1</console>
        </logger>
        <http_port>8123</http_port>
        <tcp_port>9000</tcp_port>
        <mysql_port>9004</mysql_port>
        <postgresql_port>9005</postgresql_port>
        <listen_host>::</listen_host>
        <max_connections>4096</max_connections>
        <keep_alive_timeout>3</keep_alive_timeout>
        <max_concurrent_queries>100</max_concurrent_queries>
        <uncompressed_cache_size>8589934592</uncompressed_cache_size>
        <mark_cache_size>5368709120</mark_cache_size>
        <path>/var/lib/clickhouse/</path>
        <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
        <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>
        <users_config>users.xml</users_config>
        <default_profile>default</default_profile>
        <default_database>default</default_database>
        <timezone>UTC</timezone>
        <mlock_executable>false</mlock_executable>
        <remote_servers>
            <logs>
                <shard>
                    <replica>
                        <host>clickhouse</host>
                        <port>9000</port>
                    </replica>
                </shard>
            </logs>
        </remote_servers>
    </clickhouse>

  users.xml: |
    <?xml version="1.0"?>
    <clickhouse>
        <profiles>
            <default>
                <max_memory_usage>10000000000</max_memory_usage>
                <use_uncompressed_cache>0</use_uncompressed_cache>
                <load_balancing>random</load_balancing>
            </default>
            <readonly>
                <readonly>1</readonly>
            </readonly>
        </profiles>
        <users>
            <default>
                <password></password>
                <networks>
                    <ip>::/0</ip>
                </networks>
                <profile>default</profile>
                <quota>default</quota>
            </default>
        </users>
        <quotas>
            <default>
                <interval>
                    <duration>3600</duration>
                    <queries>0</queries>
                    <errors>0</errors>
                    <result_rows>0</result_rows>
                    <read_rows>0</read_rows>
                    <execution_time>0</execution_time>
                </interval>
            </default>
        </quotas>
    </clickhouse>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  namespace: social-proof-system
  labels:
    app: clickhouse
    tier: analytics
    environment: ${ENVIRONMENT}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
        tier: analytics
        environment: ${ENVIRONMENT}
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:23.8-alpine
          ports:
            - containerPort: 8123
              protocol: TCP
              name: http
            - containerPort: 9000
              protocol: TCP
              name: native
            - containerPort: 9004
              protocol: TCP
              name: mysql
            - containerPort: 9005
              protocol: TCP
              name: postgresql
          env:
            - name: CLICKHOUSE_DB
              value: "${CLICKHOUSE_DATABASE}"
            - name: CLICKHOUSE_USER
              value: "default"
            - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
              value: "1"
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          volumeMounts:
            - name: clickhouse-storage
              mountPath: /var/lib/clickhouse
            - name: clickhouse-config
              mountPath: /etc/clickhouse-server/config.xml
              subPath: config.xml
            - name: clickhouse-config
              mountPath: /etc/clickhouse-server/users.xml
              subPath: users.xml
          livenessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: clickhouse-storage
          persistentVolumeClaim:
            claimName: clickhouse-pvc
        - name: clickhouse-config
          configMap:
            name: clickhouse-config

---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: social-proof-system
  labels:
    app: clickhouse
    tier: analytics
    environment: ${ENVIRONMENT}
spec:
  type: ClusterIP
  ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
      name: http
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: native
    - port: 9004
      targetPort: 9004
      protocol: TCP
      name: mysql
    - port: 9005
      targetPort: 9005
      protocol: TCP
      name: postgresql
  selector:
    app: clickhouse
