apiVersion: v1
kind: ConfigMap
metadata:
  name: social-proof-config
  namespace: social-proof-system
  labels:
    app: social-proof-app
    environment: ${{ vars.ENVIRONMENT }}
data:
  # Environment
  NODE_ENV: "${{ vars.NODE_ENV }}"

  # Database Configuration
  DATABASE_URL: "postgresql://${{ vars.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/${{ vars.POSTGRES_DB }}"

  # Redis Configuration
  REDIS_URL: "redis://redis:6379"

  # Kafka Configuration
  KAFKA_BROKERS: "kafka:9092"

  # ClickHouse Configuration
  CLICKHOUSE_URL: "http://clickhouse:8123"
  CLICKHOUSE_DATABASE: "${{ vars.CLICKHOUSE_DATABASE }}"

  # Service URLs
  INTEGRATIONS_SERVICE_URL: "http://integrations-service:3001"
  NOTIFICATION_STREAM_SERVICE_URL: "http://notification-stream-service:3002"
  NOTIFICATIONS_SERVICE_URL: "http://notifications-service:3003"
  USERS_SERVICE_URL: "http://users-service:3004"
  ANALYTICS_SERVICE_URL: "http://analytics-service:3005"
  BILLING_SERVICE_URL: "http://billing-service:3006"

  # Application Configuration
  LOG_LEVEL: "${{ vars.LOG_LEVEL }}"
  METRICS_ENABLED: "${{ vars.METRICS_ENABLED }}"
  TRACING_ENABLED: "${{ vars.TRACING_ENABLED }}"

  # Health Check Configuration
  HEALTH_CHECK_TIMEOUT: "${{ vars.HEALTH_CHECK_TIMEOUT }}"
  HEALTH_CHECK_INTERVAL: "${{ vars.HEALTH_CHECK_INTERVAL }}"
