apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-proof-app
  namespace: social-proof-system
  labels:
    app: social-proof-app
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-proof-app
  template:
    metadata:
      labels:
        app: social-proof-app
        environment: staging
    spec:
      containers:
      - name: social-proof-app
        image: gcr.io/social-proof-app-gcp/social-proof-app:implement-billing-service-9ecd48bd
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: social-proof-config
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: social-proof-config
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: social-proof-config
              key: REDIS_URL
        - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: social-proof-secrets
              key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        - name: CLERK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: social-proof-secrets
              key: CLERK_SECRET_KEY
        - name: NEXT_PUBLIC_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: social-proof-secrets
              key: NEXT_PUBLIC_SUPABASE_URL
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: social-proof-secrets
              key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        - name: SUPABASE_KEY
          valueFrom:
            secretKeyRef:
              name: social-proof-secrets
              key: SUPABASE_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Temporarily disabled health probes due to HTTPS/HTTP configuration issues
        # livenessProbe:
        #   httpGet:
        #     path: /api/health
        #     port: 3000
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /api/health
        #     port: 3000
        #     scheme: HTTP
        #   initialDelaySeconds: 5
        #   periodSeconds: 5 