apiVersion: v1
kind: Secret
metadata:
  name: social-proof-secrets
  namespace: social-proof-system
  labels:
    app: social-proof-app
    environment: ${{ vars.ENVIRONMENT }}
type: Opaque
stringData:
  # Secrets will be base64 encoded automatically by Kubernetes when using stringData
  # Clerk Authentication
  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}

  # SendGrid
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

  # Stripe
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}

  # Database passwords
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

  # JWT Secrets
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

  # API Keys for external services
  SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
  SHOPIFY_API_SECRET: ${{ secrets.SHOPIFY_API_SECRET }}
  WOOCOMMERCE_API_KEY: ${{ secrets.WOOCOMMERCE_API_KEY }}
  WOOCOMMERCE_API_SECRET: ${{ secrets.WOOCOMMERCE_API_SECRET }}

  # Grafana secrets (auto-generated values)
  GRAFANA_ADMIN_PASSWORD: "admin123"
  GRAFANA_SECRET_KEY: "auto-generated-grafana-secret-key-32chars"

---
apiVersion: v1
kind: Secret
metadata:
  name: gcr-json-key
  namespace: social-proof-system
  labels:
    app: social-proof-app
    environment: ${{ vars.ENVIRONMENT }}
type: kubernetes.io/dockerconfigjson
stringData:
  # Docker registry credentials - will be generated in GitHub Actions workflow
  .dockerconfigjson: |
    {
      "auths": {
        "gcr.io": {
          "auth": "${{ secrets.GCR_AUTH_TOKEN }}"
        }
      }
    }
