apiVersion: v1
kind: Secret
metadata:
  name: users-service-secrets
  namespace: social-proof-app
type: Opaque
data:
  # These are placeholder values. Do NOT store actual secrets in version control.
  # These values should be supplied via CI/CD pipeline or external secret management
  clerk-api-key: "${CLERK_API_KEY_BASE64}"
  jwt-secret: "${JWT_SECRET_BASE64}"
  postgres-user: "${POSTGRES_USER_BASE64}"
  postgres-password: "${POSTGRES_PASSWORD_BASE64}" 