apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: social-proof-app
  labels:
    app: users-service
    component: microservice
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3001"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: users-service 