apiVersion: v1
kind: Service
metadata:
  name: integrations-service
  namespace: social-proof-system
  labels:
    app: integrations-service
    tier: backend
    environment: staging
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: integrations-service
  sessionAffinity: None
  externalTrafficPolicy: Cluster
