apiVersion: v1
kind: Service
metadata:
  name: notifications-service
  namespace: social-proof-system
  labels:
    app: notifications-service
    tier: backend
    environment: staging
spec:
  type: ClusterIP
  ports:
    - port: 3003
      targetPort: 3003
      protocol: TCP
      name: http
  selector:
    app: notifications-service
  sessionAffinity: None
