apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: social-proof-system
  labels:
    app: users-service
    tier: backend
    environment: staging
spec:
  type: ClusterIP
  ports:
    - port: 3004
      targetPort: 3004
      protocol: TCP
      name: http
  selector:
    app: users-service
  sessionAffinity: None
