version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: ./services/api-gateway/Dockerfile
    image: social-proof/api-gateway:${TAG:-latest}
    ports:
      - "${API_GATEWAY_PORT:-8000}:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - INTEGRATIONS_SERVICE_URL=http://integrations:3001
      - NOTIFICATIONS_SERVICE_URL=http://notifications:3002
      - FRONTEND_SERVICE_URL=http://frontend:3000
      - REDIS_URL=${REDIS_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - social-proof-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Integrations Service
  integrations:
    build:
      context: .
      dockerfile: ./services/integrations/Dockerfile
    image: social-proof/integrations:${TAG:-latest}
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_CLIENT_ID=integrations-service
      - KAFKA_GROUP_ID=integrations-service-group
      - SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
      - SHOPIFY_API_SECRET=${SHOPIFY_API_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - social-proof-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Notifications Service
  notifications:
    build:
      context: .
      dockerfile: ./services/notifications/Dockerfile
    image: social-proof/notifications:${TAG:-latest}
    environment:
      - NODE_ENV=production
      - PORT=3002
      - DATABASE_URL=${DATABASE_URL}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_CLIENT_ID=notifications-service
      - KAFKA_GROUP_ID=notifications-service-group
      - REDIS_URL=${REDIS_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - social-proof-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: ./services/notification-stream-service/Dockerfile
    image: social-proof/frontend:${TAG:-latest}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=${REDIS_URL}
      - INTEGRATIONS_SERVICE_URL=http://integrations:3001
      - NOTIFICATIONS_SERVICE_URL=http://notifications:3002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - social-proof-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  social-proof-network:
    driver: bridge 