version: '3.8'

services:
  # Integrations Service
  integrations:
    build:
      context: ./services/integrations
      dockerfile: Dockerfile.basic
    container_name: social-proof-integrations
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - social-proof-network

  # Notification Stream Service
  notification-stream:
    build:
      context: ./services/notification-stream-service
      dockerfile: Dockerfile.basic
    container_name: social-proof-notification-stream
    restart: unless-stopped
    ports:
      - "3002:3002"
    networks:
      - social-proof-network

  # Notifications Service
  notifications:
    build:
      context: ./services/notifications
      dockerfile: Dockerfile.basic
    container_name: social-proof-notifications
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - social-proof-network

  # Users Service
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile.basic
    container_name: social-proof-users
    restart: unless-stopped
    ports:
      - "3003:3001"
    networks:
      - social-proof-network

  # Analytics Service
  analytics:
    build:
      context: ./services/analytics
      dockerfile: Dockerfile.basic
    container_name: social-proof-analytics
    restart: unless-stopped
    ports:
      - "3004:3003"
    networks:
      - social-proof-network

  # Billing Service
  billing:
    build:
      context: ./services/billing
      dockerfile: Dockerfile.basic
    container_name: social-proof-billing
    restart: unless-stopped
    ports:
      - "3005:3004"
    networks:
      - social-proof-network

# Networks for service communication
networks:
  social-proof-network:
    driver: bridge 