version: '3.8'

services:
  # Very basic container for integrations service
  integrations:
    build:
      context: ./services/integrations
      dockerfile: Dockerfile.basic
    container_name: social-proof-integrations-basic
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - social-proof-network

# Networks for service communication
networks:
  social-proof-network:
    driver: bridge 