apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-frontend
  namespace: social-proof-system
  labels:
    app: nextjs-frontend
    tier: frontend
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-frontend
  template:
    metadata:
      labels:
        app: nextjs-frontend
        tier: frontend
        environment: staging
    spec:
      containers:
        - name: nextjs-frontend
          image: nginx:alpine
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: PORT
              value: "3000"
          envFrom:
            - configMapRef:
                name: social-proof-config
            - secretRef:
                name: social-proof-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: nginx-html
          configMap:
            name: nginx-html
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
